appNmae: cartservice
appImage: gcr.io/google-samples/microservices-demo/cartservice
appVersion: v.0.2.3
appReplicas: 2
containerPort: 7070
containerEnvVars:
env:
- name: PORT
    value: '7070'
- name: REDIS_ADDR
    value: 'redis-cart:6379'

servicePort: 7070
serviceType: clusetrIP