appNmae: frontend
appImage: gcr.io/google-samples/microservices-demo/frontend
appVersion: v.0.2.3
appReplicas: 2
containerPort: 8080
containerEnvVars:
- name: PORT
  value: "8080"
- name: PRODUCT_CATALOGUE_SERVICE_ADDR
  value: "productcatalogueservice:3550"
- name: SHIPPING_SERVICE_ADDR
  value: "shippingservice:50051"
- name: CURRENCY_SERVICE_ADDR
  value: ''currencyservice:7000''
- name: CART_SERVICE_ADDR
  value: "cartservice:7070"
- name: RECOMMNENDATION_SERVICE_ADDR
  value: "recommendation:8080"
- name: CHECKOUT_SERVICE_ADDR
  value: "checkoutservice:5050"
- name: AD_SERVICE_ADDR
  value: 'adservice:9555'

servicePort: 80
serviceType: Loadbalancer