apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.appName }}
  ports:
  - protocol: TCP
    ports: {{ .Values.servicePort }}
    targetPort: {{ .Values.containerPort }}